Feature/integration project frontend 05
pdrflp0/integration_project_frontend pull request #8
Opened 2024-06-21 16:59 UTC by pdrflp0

2024-06-22 15:57 UTC, XxTaro requested changes
Foi realizado o code review e foi identificado pontos para melhoria e/ou correção

2024-06-22 15:57 UTC, gustavo-lopes-dev commented on src/main/java/br/eletra/frontend/controller/ScreenController.java
> +    Accordion accordion;
Favor, não deixar as varíaveis sem os modificadores. Como é usado para os testes, deixar todos como "protected", com esse modificador, é possível acessar as variaveis dentro das classes que compartilham o mesmo pacote

2024-06-22 15:57 UTC, gustavo-lopes-dev commented on src/main/java/br/eletra/frontend/controller/ScreenController.java
>      }
Favor, não deixar os métodos sem os modificadores. Como é usado para os testes, deixar todos como "protected", com esse modificador, é possível acessar esses métodos dentro das classes que compartilham o mesmo pacote

2024-06-22 15:57 UTC, XxTaro commented on src/test/java/br/eletra/frontend/controller/ScreenControllerTest.java
Por favor, não esquecer de colocar a anotação After nas classes de testes. Ele é fundamental pra limpar as instâncias criadas na anotação Before e evitar problemas com memória

2024-06-22 15:57 UTC, XxTaro commented on src/test/java/br/eletra/frontend/services/CategoryServicesTest.java
Por favor, não esquecer de colocar a anotação After nas classes de testes. Ele é fundamental pra limpar as instâncias criadas na anotação Before e evitar problemas com memória

2024-06-22 15:57 UTC, XxTaro commented on src/test/java/br/eletra/frontend/services/LineServicesTest.java
Por favor, não esquecer de colocar a anotação After nas classes de testes. Ele é fundamental pra limpar as instâncias criadas na anotação Before e evitar problemas com memória

2024-06-22 15:57 UTC, gustavo-lopes-dev commented on src/test/java/br/eletra/frontend/services/ModelServicesTest.java
Por favor, não esquecer de colocar a anotação After nas classes de testes. Ele é fundamental pra limpar as instâncias criadas na anotação Before e evitar problemas com memória

2024-06-22 15:57 UTC, gustavo-lopes-dev commented on src/test/java/br/eletra/frontend/controller/ScreenControllerTest.java
> +    }
Na linha de código `controller.titledPaneLines.setDisable(true);` é uma falha no teste pois dentro do método initialize() ocorre o mesmo set, favor, corrigir essa falha

2024-06-22 15:57 UTC, XxTaro commented on src/test/java/br/eletra/frontend/controller/ScreenControllerTest.java
> +    }
Não consegui compreender a necessidades desses testes e podem ser apagados

2024-06-22 15:57 UTC, gustavo-lopes-dev commented on src/test/java/br/eletra/frontend/services/CategoryServicesTest.java
> +        List<CategoryDTO> mockCategoryList = mockGson.fromJson(response.readEntity(String.class), mockCategoryListType);
essa variável não é usada, favor apagar

2024-06-25 17:14 UTC, pdrflp0 commented on src/main/java/br/eletra/frontend/controller/ScreenController.java
> +    Accordion accordion;
Corrigido ✅

2024-06-25 17:15 UTC, pdrflp0 commented on src/main/java/br/eletra/frontend/controller/ScreenController.java
>      }
Corrigido ✅

2024-06-25 17:20 UTC, pdrflp0 commented on src/test/java/br/eletra/frontend/controller/ScreenControllerTest.java
Corrigido ✅

2024-06-25 17:21 UTC, pdrflp0 commented on src/test/java/br/eletra/frontend/services/CategoryServicesTest.java
Corrigido ✅

2024-06-25 17:21 UTC, pdrflp0 commented on src/test/java/br/eletra/frontend/services/LineServicesTest.java
Corrigido ✅

2024-06-25 17:21 UTC, pdrflp0 commented on src/test/java/br/eletra/frontend/services/ModelServicesTest.java
Corrigido ✅

2024-06-25 17:31 UTC, pdrflp0 commented on src/test/java/br/eletra/frontend/controller/ScreenControllerTest.java
> +    }
Corrigido ✅

2024-06-25 17:31 UTC, pdrflp0 commented on src/test/java/br/eletra/frontend/controller/ScreenControllerTest.java
> +    }
Corrigido ✅

2024-06-25 17:43 UTC, pdrflp0 commented on src/test/java/br/eletra/frontend/services/CategoryServicesTest.java
> +        List<CategoryDTO> mockCategoryList = mockGson.fromJson(response.readEntity(String.class), mockCategoryListType);
Corrigido ✅

2024-06-30 15:35 UTC, XxTaro approved these changes

2024-06-30 21:39 UTC, merged